Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -11,67 +11,59 @@ BASE=$1
 SENSOR=$2
 ARCH="$(uname -m)"
 echo $ARCH
-echo "
-______ _____________   _________ ________ _______ ________ _______ ________
-___  / ____  _/___  | / /__  __ \___  __ \__  __ \___  __ )__  __ \___  __/
-__  /   __  /  __   |/ / _  / / /__  /_/ /_  / / /__  __  |_  / / /__  /   
-_  /_____/ /   _  /|  /  / /_/ / _  _, _/ / /_/ / _  /_/ / / /_/ / _  /    
-/_____//___/   /_/ |_/   \____/  /_/ |_|  \____/  /_____/  \____/  /_/     
-                    
-                            http://linorobot.org                                                                          
-"
+
 if [ "$3" != "test" ]
-    then
-        if [ "$*" == "" ]
-            then
-                echo "No arguments provided"
-                echo
-                echo "Example: $ ./install.sh 2wd xv11"
-                echo
-                exit 1
+then
+if [ "$*" == "" ]
+then
+echo "No arguments provided"
+echo
+echo "Example: $ ./install.sh 2wd xv11"
+echo
+exit 1
                 
-        elif [[ "$1" != "2wd" && "$1" != "4wd" && "$1" != "mecanum" && "$1" != "ackermann" ]]
-            then
-                echo "Invalid linorobot base: $1"
-                echo
-                echo "Valid Options:"
-                echo "2wd"
-                echo "4wd"
-                echo "ackermann"
-                echo "mecanum"
-                echo
-                exit 1
+    elif [[ "$1" != "2wd" && "$1" != "4wd" && "$1" != "mecanum" && "$1" != "ackermann" ]]
+        then
+            echo "Invalid linorobot base: $1"
+            echo
+            echo "Valid Options:"
+            echo "2wd"
+            echo "4wd"
+            echo "ackermann"
+            echo "mecanum"
+            echo
+            exit 1
 
-        elif [[ "$2" != "xv11" && "$2" != "rplidar" && "$2" != "ydlidar" && "$2" != "hokuyo" && "$2" != "kinect" && "$2" != "realsense" ]]
-            then
-                echo "Invalid linorobot sensor: $2"
-                echo
-                echo "Valid Options:"
-                echo "hokuyo"
-                echo "kinect"
-                echo "lms1xx"
-                echo "realsense"
-                echo "rplidar"
-                echo "xv11"
-                echo "ydlidar"
-                echo
-                exit 1
-        
-        elif [[ "$ARCH" != "x86_64" && "$2" == "realsense" ]]
-            then
-                echo "Intel Realsense R200 is not supported in $ARCH architecture."
-                exit 1
+    elif [[ "$2" != "xv11" && "$2" != "rplidar" && "$2" != "ydlidar" && "$2" != "hokuyo" && "$2" != "kinect" && "$2" != "realsense" ]]
+        then
+            echo "Invalid linorobot sensor: $2"
+            echo
+            echo "Valid Options:"
+            echo "hokuyo"
+            echo "kinect"
+            echo "lms1xx"
+            echo "realsense"
+            echo "rplidar"
+            echo "xv11"
+            echo "ydlidar"
+            echo
+            exit 1
+    
+    elif [[ "$ARCH" != "x86_64" && "$2" == "realsense" ]]
+        then
+            echo "Intel Realsense R200 is not supported in $ARCH architecture."
+            exit 1
 
-        fi
+    fi
 
-        echo
-        echo -n "You are installing ROS-$ROSDISTRO Linorobot for $BASE base with a $SENSOR sensor. Enter [y] to continue. " 
-        read reply
-        if [[ "$reply" != "y" && "$reply" != "Y" ]]
-            then
-                echo "Wrong input. Exiting now"
-                exit 1
-        fi
+    echo
+    echo -n "You are installing ROS-$ROSDISTRO Linorobot for $BASE base with a $SENSOR sensor. Enter [y] to continue. " 
+    read reply
+    if [[ "$reply" != "y" && "$reply" != "Y" ]]
+        then
+            echo "Wrong input. Exiting now"
+            exit 1
+    fi
 fi
 
 echo
@@ -85,10 +77,10 @@ openssh-server \
 python-setuptools \
 python-dev \
 build-essential \
-python-gudev
-
-sudo easy_install pip
-sudo python2.7 -m pip install -U platformio
+gir1.2-gudev-1.0
+sudo apt install python-is-python3
+sudo apt install python3-pip
+sudo pip3 install -U platformio
 sudo rm -rf $HOME/.platformio/
 
 source /opt/ros/$ROSDISTRO/setup.bash
